name: Tests

on:
  pull_request:
  push:
     branches:
     - main

jobs:
  tests:
    runs-on: macOS-12
    env:
        DEVELOPER_DIR: /Applications/Xcode_14.0.app/Contents/Developer

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        run: swift test
